#!/usr/bin/env bash
# Fluvia lure (Run 2) — turnkey provisioning for a FRESH Ubuntu 24.04 droplet.
# Usage (from your machine):
#   scp -r fluvia-deploy root@<IP>:/root/
#   ssh root@<IP> 'cd /root/fluvia-deploy && bash setup.sh'
# Target: full stack live in <6 minutes. Domain + TLS (Caddy/LE) attach afterwards.
# Everything [FAKE]: no real money, crypto, or data. Cowrie userdb = entropic filter.
#
# Stack: fluvi-web (lure) + cowrie (:22) + fake-c2 (sinkhole responder) + suricata (JA3/JA4)
#        + host-side analysis scripts (scripts/analyze.sh).
set -euo pipefail
cd "$(dirname "$0")"

echo "== [1/7] installing docker + compose + nftables =="
export DEBIAN_FRONTEND=noninteractive
# fresh DO droplets run unattended-upgrades on first boot — DPkg lock timeout handles it
apt-get -o DPkg::Lock::Timeout=180 update -qq
apt-get -o DPkg::Lock::Timeout=180 install -y -qq docker.io docker-compose-v2 nftables
systemctl enable --now docker >/dev/null 2>&1 || true

echo "== [2/7] moving host sshd to 64221 (frees :22 for the Cowrie honeypot) =="
if ! grep -q "^Port 64221" /etc/ssh/sshd_config; then
  cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
  echo "Port 64221" >> /etc/ssh/sshd_config
fi
# Ubuntu 24.04: systemd ssh.socket activation holds :22 even after sshd moves —
# stop the socket or docker cannot bind the honeypot port
systemctl disable --now ssh.socket >/dev/null 2>&1 || true
systemctl restart ssh || systemctl restart sshd

echo "== [3/7] building lure + responder images =="
docker build -q -t fluvi-web ./fluvi-app
docker build -q -t fluvi-fakec2 ./fake-c2

echo "== [4/7] preparing dirs + compose env =="
mkdir -p cowrie/log evidence classify/eve
chmod -R 777 cowrie/log evidence classify/eve   # container non-root users must WRITE here
chmod 644 cowrie/userdb.txt                     # cowrie user must READ it (ASCII parser)
IFACE="$(ip route | awk '/^default/{print $5; exit}')"; IFACE="${IFACE:-eth0}"
cat > .env <<EOF
# generated by setup.sh — read by docker compose
IFACE=$IFACE
SINK_PORT=9001
EOF
echo "  iface=$IFACE"

echo "== [5/7] starting stack (cowrie + suricata images pull on first run) =="
docker compose up -d --quiet-pull || docker compose up -d

echo "== [6/7] installing the C2 sinkhole redirect =="
bash sinkhole/apply.sh targets.txt 9001

echo "== [7/7] health checks =="
sleep 5
curl -sf -o /dev/null http://127.0.0.1/ && echo "  web lure :80          OK"
curl -sf -o /dev/null http://127.0.0.1/about && echo "  lure pages            OK"
curl -sf -o /dev/null http://127.0.0.1/llms.txt && echo "  agent bait /llms.txt  OK"
docker compose ps --format 'table {{.Name}}\t{{.Status}}'
echo
bash verify-features.sh || true

echo
echo "== done =="
echo "  web lure (Next.js):  http://<ip>/     (Cowrie SSH honeypot :22, entropic filter)"
echo "  fake-C2 sinkhole:    $(grep -vc '^#' sinkhole/targets.txt) target(s) -> :9001 (evidence/fakec2.jsonl)"
echo "  ja3/ja4:             classify/eve/eve.json (container fluvi-ja3)"
echo "  analysis:            bash scripts/analyze.sh"
echo "  admin ssh:           ssh -p 64221 root@<ip>"
echo "  next: point the .finance domain at this IP + Caddy/LE TLS (CT-log discovery channel)"
