#!/usr/bin/env bash
# Fluvia lure (Run 2) — turnkey provisioning for a FRESH Ubuntu 24.04 droplet.
#
#   scp -r fluvia-deploy root@<IP>:/root/
#   ssh root@<IP> 'cd /root/fluvia-deploy && DOMAIN=fluvia.example bash setup.sh'
#
# Prereqs: the domain's A records must ALREADY point at this droplet (see
# scripts/dns-porkbun.sh --set) or Caddy cannot get a certificate.
# Target: full stack + TLS live in <7 minutes.
# Everything [FAKE]: no real money, crypto, or data. Cowrie userdb = entropic filter.
#
# Stack: caddy (TLS :80/:443) -> fluvi-web (lure) + cowrie (:22) + fake-c2 (sinkhole
#        responder) + suricata (JA3/JA4) + host analysis scripts + egress lockdown.
#
# Env: DOMAIN (required) · ACME_STAGING=1 (use LE staging, for dry runs) ·
#      SKIP_EGRESS=1 (leave egress open) · ACME_EMAIL (default ops@DOMAIN)
set -euo pipefail
cd "$(dirname "$0")"

DOMAIN="${DOMAIN:-}"
[ -n "$DOMAIN" ] || { echo "ERROR: set DOMAIN=<your.domain> (A records must point here first)" >&2; exit 1; }
ACME_EMAIL="${ACME_EMAIL:-ops@$DOMAIN}"

echo "== [1/9] installing docker + compose + nftables =="
export DEBIAN_FRONTEND=noninteractive
# fresh DO droplets run unattended-upgrades on first boot — DPkg lock timeout handles it
apt-get -o DPkg::Lock::Timeout=180 update -qq
apt-get -o DPkg::Lock::Timeout=180 install -y -qq docker.io docker-compose-v2 nftables dnsutils
systemctl enable --now docker >/dev/null 2>&1 || true

echo "== [2/9] moving host sshd to 64221 (frees :22 for the Cowrie honeypot) =="
if ! grep -q "^Port 64221" /etc/ssh/sshd_config; then
  cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
  echo "Port 64221" >> /etc/ssh/sshd_config
fi
# Ubuntu 24.04: systemd ssh.socket activation holds :22 even after sshd moves —
# stop the socket or docker cannot bind the honeypot port
systemctl disable --now ssh.socket >/dev/null 2>&1 || true
systemctl restart ssh || systemctl restart sshd

echo "== [3/9] building lure + responder images =="
docker build -q -t fluvi-web ./fluvi-app
docker build -q -t fluvi-fakec2 ./fake-c2

echo "== [4/9] preparing dirs + compose env =="
mkdir -p cowrie/log evidence classify/eve caddy/data caddy/log
chmod -R 777 cowrie/log evidence classify/eve caddy   # container users must WRITE here
chmod 644 cowrie/userdb.txt                           # cowrie user must READ it (ASCII parser)
IFACE="$(ip route | awk '/^default/{print $5; exit}')"; IFACE="${IFACE:-eth0}"
# NB: written with printf, not a heredoc — a backtick or $() in a heredoc comment gets
# executed by the shell and dumps command output straight into the file.
{
  echo "# generated by setup.sh — read by docker compose at every call"
  echo "DOMAIN=$DOMAIN"
  echo "IFACE=$IFACE"
  echo "SINK_PORT=9001"
} > .env
docker compose config -q || { echo "ERROR: docker compose rejects .env" >&2; exit 1; }
echo "  domain=$DOMAIN iface=$IFACE"

echo "== [5/9] generating Caddyfile =="
if [ "${ACME_STAGING:-0}" = "1" ]; then
  CA_LINE=$'\tacme_ca https://acme-staging-v02.api.letsencrypt.org/directory'
  echo "  ACME: STAGING (certs are not trusted — dry run only)"
else
  CA_LINE=""
fi
sed -e "s|__DOMAIN__|$DOMAIN|g" \
    -e "s|__ACME_EMAIL__|$ACME_EMAIL|g" \
    -e "s|__ACME_CA_LINE__|$CA_LINE|g" Caddyfile.tmpl > Caddyfile
grep -q "__" Caddyfile && { echo "ERROR: Caddyfile still has placeholders" >&2; exit 1; }

echo "== [6/9] starting stack (cowrie + suricata images pull on first run) =="
docker compose up -d --quiet-pull || docker compose up -d

echo "== [7/9] installing the C2 sinkhole redirect =="
bash sinkhole/apply.sh targets.txt 9001

echo "== [8/9] waiting for the TLS certificate (CT-log discovery channel) =="
ok=0
for i in $(seq 1 30); do
  code=$(curl -sk -o /dev/null -w "%{http_code}" --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN/" --max-time 8 || true)
  if [ "$code" = "200" ]; then ok=1; echo "  https://$DOMAIN  OK (attempt $i)"; break; fi
  sleep 6
done
if [ "$ok" = "0" ]; then
  echo "  WARN: no 200 yet from https://$DOMAIN — caddy logs:" >&2
  docker logs --tail 25 fluvi-caddy 2>&1 | sed 's/^/    /' >&2
  echo "  (check that the A records point here and that 80/443 are reachable)" >&2
fi

echo "== [9/9] egress lockdown + health checks =="
if [ "${SKIP_EGRESS:-0}" = "1" ]; then
  echo "  SKIP_EGRESS=1 — egress left open"
else
  bash sinkhole/egress.sh
fi
docker compose ps --format 'table {{.Name}}\t{{.Status}}'
echo
DOMAIN="$DOMAIN" bash verify-features.sh || true

echo
echo "== done =="
echo "  web lure:            https://$DOMAIN/     (Cowrie SSH honeypot :22, entropic filter)"
echo "  dns check:           bash scripts/dns-porkbun.sh check $DOMAIN <this-ip>"
echo "  fake-C2 sinkhole:    $(grep -vc '^#' sinkhole/targets.txt || true) target(s) -> :9001 (evidence/fakec2.jsonl)"
echo "  ja3/ja4:             classify/eve/eve.json (container fluvi-ja3)"
echo "  analysis:            bash scripts/analyze.sh"
echo "  admin ssh:           ssh -p 64221 root@<ip>"
